### ISSUE TITLE
consider releasing a stable version

### ISSUE THREAD

**Issue by decathorpe** [elementary/cmake-modules#2]
This issue has previously been tracked at <https://bugs.launchpad.net/elementaryos/+bug/1639931>.

**Comment by decathorpe** [comment]
I guess this issue is kind of dead, since all projects are moving to `meson` for the juno release anyway?

**Comment by tintou** [comment]
Yes, linking to the meson port project

**Comment by codygarver** [comment]
The last master that still depended on `cmake-elementary`, `pantheon-agent-geoclue2` was just ported to Meson so this will not be necessary anymore.
